/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemasystem;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author newac
 */
public class BuySnacks extends javax.swing.JFrame {

    /**
     * Creates new form BuySnacks
     */
    
    private boolean array[][];
    private customer cus;
    private movie mov;
    
    double total_amount = 0;
    int items = 0;
    
    
    public BuySnacks() {
        initComponents();
        
        table.getTableHeader().setBackground(Color.orange);
        table.getTableHeader().setForeground(Color.black);
        Font font = new Font("Candara", Font.BOLD, 18);
        table.getTableHeader().setFont(font);
        table.getTableHeader().setSize(40, 40);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer(); centerRenderer.setHorizontalAlignment( JLabel.CENTER ); table.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
    }

    BuySnacks(boolean[][] tempvalue, movie m, customer c) {
        initComponents();
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        model.setValueAt(0, 0, 3);
        table.getTableHeader().setBackground(Color.orange);
        table.getTableHeader().setForeground(Color.black);
        Font font = new Font("Candara", Font.BOLD, 18);
        table.getTableHeader().setFont(font);
        table.getTableHeader().setSize(40, 40);
        
        mov = new movie(m.getId(),m.getTitle(),m.getGenre(),m.getRating(),m.getDuration(),m.getDate(),m.getTime(),m.getHall());
        cus = new customer(c.getName(),c.getCnic(),c.getAddress(),c.getPhone());
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer(); centerRenderer.setHorizontalAlignment( JLabel.CENTER ); table.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        centerRenderer = new DefaultTableCellRenderer(); centerRenderer.setHorizontalAlignment( JLabel.CENTER ); table.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        
        array = new boolean[tempvalue.length][tempvalue[0].length];
        for (int i = 0; i < tempvalue.length; i++) {
            for (int j = 0; j < tempvalue[0].length; j++) {
                array[i][j] = tempvalue[i][j];
            }
        }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton19 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setBackground(new java.awt.Color(204, 0, 0));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemasystem/previous (2) (1).png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, -1));

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\minus (1).png")); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\minus (1).png")); // NOI18N
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\minus (1).png")); // NOI18N
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, -1, -1));

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\minus (1).png")); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, -1, -1));

        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\minus (1).png")); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setFocusPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, -1));

        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\minus (1).png")); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setFocusPainted(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, -1, -1));

        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\minus (1).png")); // NOI18N
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setFocusPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 630, -1, -1));

        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\minus (1).png")); // NOI18N
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setFocusPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 690, -1, -1));

        jButton18.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\minus (1).png")); // NOI18N
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setFocusPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Candara", 3, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("BUY SNACKS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\plus.png")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\plus.png")); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\plus.png")); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\plus.png")); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 690, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\plus.png")); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\plus.png")); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\plus.png")); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\plus.png")); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\plus.png")); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, -1, -1));

        table.setBackground(new java.awt.Color(0, 0, 0));
        table.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"POPCORN", "SALTED",  new Double(150.0), null},
                {"POPCORN", "BUTTER",  new Double(180.0),  new Integer(0)},
                {"POPCORN", "CARAMEL",  new Double(200.0),  new Integer(0)},
                {"FRENCH FRIES", "PLAIN",  new Double(100.0),  new Integer(0)},
                {"FRENCH FRIES", "MASALA",  new Double(120.0),  new Integer(0)},
                {"FRENCH FRIES", "MAYO GARLIC",  new Double(150.0),  new Integer(0)},
                {"SOFT DRINK", "PEPSI",  new Double(60.0),  new Integer(0)},
                {"SOFT DRINK", "SPRITE",  new Double(60.0),  new Integer(0)},
                {"SOFT DRINK", "FANTA",  new Double(60.0),  new Integer(0)}
            },
            new String [] {
                "ITEM", "CATEGORY", "PRICE", "QUANTITY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setOpaque(false);
        table.setRowHeight(60);
        table.setSelectionBackground(new java.awt.Color(255, 153, 0));
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 680, 570));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\popcorn (1).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\french-fries (1).png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 140, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\soft-drink (1).png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, -1, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("TOTAL AMOUNT: 0.0");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("ITEMS IN CART: 0");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 350, 10));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemasystem/right-arrow (1) (1).png"))); // NOI18N
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setFocusPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 350, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\sbg.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 840, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1433, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(3, 3);
        qty++;
        model.setValueAt(qty, 3, 3);
        total_amount += 100;
        items++;
        jLabel6.setText("TOTAL AMOUNT: " + total_amount);
        jLabel7.setText("ITEMS IN CART: " + items);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new adminHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(0, 3);
        qty++;
        model.setValueAt(qty, 0, 3);
        total_amount += 150;
        items++;
        jLabel6.setText("TOTAL AMOUNT: " + total_amount);
        jLabel7.setText("ITEMS IN CART: " + items);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(1, 3);
        qty++;
        model.setValueAt(qty, 1, 3);
        total_amount += 180;
        items++;
        jLabel6.setText("TOTAL AMOUNT: " + total_amount);
        jLabel7.setText("ITEMS IN CART: " + items);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(8, 3);
        qty++;
        model.setValueAt(qty, 8, 3);
        total_amount += 60;
        items++;
        jLabel6.setText("TOTAL AMOUNT: " + total_amount);
        jLabel7.setText("ITEMS IN CART: " + items);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(2, 3);
        qty++;
        model.setValueAt(qty, 2, 3);
        total_amount += 200;
        items++;
        jLabel6.setText("TOTAL AMOUNT: " + total_amount);
        jLabel7.setText("ITEMS IN CART: " + items);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(4, 3);
        qty++;
        model.setValueAt(qty, 4, 3);
        total_amount += 120;
        items++;
        jLabel6.setText("TOTAL AMOUNT: " + total_amount);
        jLabel7.setText("ITEMS IN CART: " + items);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(5, 3);
        qty++;
        model.setValueAt(qty, 5, 3);
        total_amount += 150;
        items++;
        jLabel6.setText("TOTAL AMOUNT: " + total_amount);
        jLabel7.setText("ITEMS IN CART: " + items);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(6, 3);
        qty++;
        model.setValueAt(qty, 6, 3);
        total_amount += 60;
        items++;
        jLabel6.setText("TOTAL AMOUNT: " + total_amount);
        jLabel7.setText("ITEMS IN CART: " + items);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(7, 3);
        qty++;
        model.setValueAt(qty, 7, 3);
        total_amount += 60;
        items++;
        jLabel6.setText("TOTAL AMOUNT: " + total_amount);
        jLabel7.setText("ITEMS IN CART: " + items);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(0, 3);
        if(qty > 0) {
            qty--;
            model.setValueAt(qty, 0, 3);
            total_amount -= 150;
            items--;
            jLabel6.setText("TOTAL AMOUNT: " + total_amount);
            jLabel7.setText("ITEMS IN CART: " + items);
        }
        
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(1, 3);
        if(qty > 0) {
            qty--;
            model.setValueAt(qty, 1, 3);
            total_amount -= 180;
            items--;
            jLabel6.setText("TOTAL AMOUNT: " + total_amount);
            jLabel7.setText("ITEMS IN CART: " + items);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(2, 3);
        if(qty > 0) {
            qty--;
            model.setValueAt(qty, 2, 3);
            total_amount -= 200;
            items--;
            jLabel6.setText("TOTAL AMOUNT: " + total_amount);
            jLabel7.setText("ITEMS IN CART: " + items);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(3, 3);
        if(qty > 0) {
            qty--;
            model.setValueAt(qty, 3, 3);
            total_amount -= 100;
            items--;
            jLabel6.setText("TOTAL AMOUNT: " + total_amount);
            jLabel7.setText("ITEMS IN CART: " + items);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(4, 3);
        if(qty > 0) {
            qty--;
            model.setValueAt(qty, 4, 3);
            total_amount -= 120;
            items--;
            jLabel6.setText("TOTAL AMOUNT: " + total_amount);
            jLabel7.setText("ITEMS IN CART: " + items);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(5, 3);
        if(qty > 0) {
            qty--;
            model.setValueAt(qty, 5, 3);
            total_amount -= 150;
            items--;
            jLabel6.setText("TOTAL AMOUNT: " + total_amount);
            jLabel7.setText("ITEMS IN CART: " + items);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(6, 3);
        if(qty > 0) {
            qty--;
            model.setValueAt(qty, 6, 3);
            total_amount -= 60;
            items--;
            jLabel6.setText("TOTAL AMOUNT: " + total_amount);
            jLabel7.setText("ITEMS IN CART: " + items);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(7, 3);
        if(qty > 0) {
            qty--;
            model.setValueAt(qty, 7, 3);
            total_amount -= 60;
            items--;
            jLabel6.setText("TOTAL AMOUNT: " + total_amount);
            jLabel7.setText("ITEMS IN CART: " + items);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int qty = (int) model.getValueAt(8, 3);
        if(qty > 0) {
            qty--;
            model.setValueAt(qty, 8, 3);
            total_amount -= 60;
            items--;
            jLabel6.setText("TOTAL AMOUNT: " + total_amount);
            jLabel7.setText("ITEMS IN CART: " + items);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {
            //receeipt
            new foodReceipt(array,mov,cus,items,total_amount).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(BuySnacks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BuySnacks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BuySnacks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(BuySnacks.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuySnacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuySnacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuySnacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuySnacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuySnacks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
