/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemasystem;

import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class customerDetail extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    movie mov;
    boolean new_customer = false;
    

    public customerDetail(movie m) {
        initComponents();
        verifyButton.setVisible(false);
        //backButton.setVisible(false);
        nextButton.setVisible(false);
        nameTF.setVisible(false);
        cnicTF.setVisible(false);
        addressTF.setVisible(false);
        phoneTF.setVisible(false);
        nameLabel.setVisible(false);
        cnicLabel.setVisible(false);
        addressLabel.setVisible(false);
        phoneLabel.setVisible(false);
        idTF.setEditable(false);
        titleTF.setEditable(false);
        hallTF.setEditable(false);
        dateTF.setEditable(false);
        timeTF.setEditable(false);
        idTF.setText(Integer.toString(m.getId()));
        titleTF.setText(m.getTitle());
        hallTF.setText(m.getHall());
        dateTF.setText(m.getDate());
        timeTF.setText(m.getTime());
        mov = new movie(m.getId(),m.getTitle(),m.getGenre(),m.getRating(),m.getDuration(),m.getDate(),m.getTime(),m.getHall());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        cnicLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        cnicTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hallTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        timeTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        old = new javax.swing.JButton();
        newcustomer = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        verifyButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Details");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("SHOW DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 420, 10));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 153, 0));
        nameLabel.setText("Name:");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        cnicLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cnicLabel.setForeground(new java.awt.Color(255, 153, 0));
        cnicLabel.setText("Enter CNIC:");
        getContentPane().add(cnicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(255, 153, 0));
        addressLabel.setText("Email Address:");
        getContentPane().add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 153, 0));
        phoneLabel.setText("Phone No:");
        getContentPane().add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, -1, -1));

        nameTF.setBackground(new java.awt.Color(0, 0, 0));
        nameTF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 266, -1));

        cnicTF.setBackground(new java.awt.Color(0, 0, 0));
        cnicTF.setForeground(new java.awt.Color(255, 255, 255));
        cnicTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicTFActionPerformed(evt);
            }
        });
        getContentPane().add(cnicTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 266, -1));

        addressTF.setBackground(new java.awt.Color(0, 0, 0));
        addressTF.setForeground(new java.awt.Color(255, 255, 255));
        addressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTFActionPerformed(evt);
            }
        });
        getContentPane().add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 266, -1));

        phoneTF.setBackground(new java.awt.Color(0, 0, 0));
        phoneTF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(phoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 266, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Show ID:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        idTF.setBackground(new java.awt.Color(0, 0, 0));
        idTF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 240, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Movie Title:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        titleTF.setBackground(new java.awt.Color(0, 0, 0));
        titleTF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(titleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 240, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Hall Category:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        hallTF.setBackground(new java.awt.Color(0, 0, 0));
        hallTF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(hallTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 240, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        dateTF.setBackground(new java.awt.Color(0, 0, 0));
        dateTF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 240, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Time:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        timeTF.setBackground(new java.awt.Color(0, 0, 0));
        timeTF.setForeground(new java.awt.Color(255, 255, 255));
        timeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTFActionPerformed(evt);
            }
        });
        getContentPane().add(timeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 240, -1));

        jLabel11.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("ENTER YOUR DETAILS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        backButton.setBackground(new java.awt.Color(255, 0, 0));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemasystem/previous (2) (1).png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        nextButton.setBackground(new java.awt.Color(0, 255, 0));
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemasystem/right-arrow (1) (1).png"))); // NOI18N
        nextButton.setText("\\");
            nextButton.setBorderPainted(false);
            nextButton.setContentAreaFilled(false);
            nextButton.setFocusPainted(false);
            nextButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    nextButtonActionPerformed(evt);
                }
            });
            getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 100, -1));

            old.setBackground(new java.awt.Color(255, 255, 255));
            old.setForeground(new java.awt.Color(255, 255, 255));
            old.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\output-onlinepngtools (2).png")); // NOI18N
            old.setBorderPainted(false);
            old.setContentAreaFilled(false);
            old.setFocusPainted(false);
            old.setMaximumSize(new java.awt.Dimension(150, 150));
            old.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    oldActionPerformed(evt);
                }
            });
            getContentPane().add(old, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 200, 160));

            newcustomer.setBackground(new java.awt.Color(255, 255, 255));
            newcustomer.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\output-onlinepngtools (3).png")); // NOI18N
            newcustomer.setBorderPainted(false);
            newcustomer.setContentAreaFilled(false);
            newcustomer.setFocusPainted(false);
            newcustomer.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    newcustomerActionPerformed(evt);
                }
            });
            getContentPane().add(newcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 200, 180));

            jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
            getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 100, 470));

            jSeparator3.setBackground(new java.awt.Color(255, 153, 0));
            jSeparator3.setForeground(new java.awt.Color(255, 153, 0));
            getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 290, 10));

            verifyButton.setBackground(new java.awt.Color(51, 255, 51));
            verifyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemasystem/check (1).png"))); // NOI18N
            verifyButton.setBorderPainted(false);
            verifyButton.setContentAreaFilled(false);
            verifyButton.setFocusPainted(false);
            verifyButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    verifyButtonActionPerformed(evt);
                }
            });
            getContentPane().add(verifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 390, -1, -1));

            jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 153, 0));
            jLabel3.setText("NEW CUSTOMER");
            getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, -1, -1));

            jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 153, 0));
            jLabel4.setText("OLD CUSTOMER");
            getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, -1, -1));

            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemasystem/movies.jpg"))); // NOI18N
            getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void cnicTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicTFActionPerformed

    private void addressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTFActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        try {
            new bookMovies().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(customerDetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(customerDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if(nameTF.getText().isEmpty() || cnicTF.getText().isEmpty() || addressTF.getText().isEmpty() || phoneTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No fields can be left empty.");
        }
        else if(cnicTF.getText().length() != 13) {
            JOptionPane.showMessageDialog(this, "Invalid CNIC Number.");
        }
        else if(!addressTF.getText().contains("@")) {
            JOptionPane.showMessageDialog(this, "Invalid Email Address.");
        }
        else {
            if(new_customer) {
                try {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/orclpdb", "cinema", "cinema");
                    pst = con.prepareStatement("insert into Customer(name,cnic,email_address,phone)values(?,?,?,?) ");
                    pst.setString(1, nameTF.getText());
                    pst.setString(2, cnicTF.getText());
                    pst.setString(3, addressTF.getText());
                    pst.setString(4, phoneTF.getText());

                    pst.executeUpdate();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(customerDetail.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(customerDetail.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            /*try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/orclpdb", "cinema", "cinema");
                pst = con.prepareStatement("insert into Booking(name,cnic,title,hall_category,day,month,show_id)values(?,?,?,?) ");
                pst.setString(1, nameTF.getText());
                pst.setString(2, cnicTF.getText());
                pst.setString(3, addressTF.getText());
                pst.setString(4, phoneTF.getText());
           
                pst.executeUpdate();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(customerDetail.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(customerDetail.class.getName()).log(Level.SEVERE, null, ex);
            }*/
                
            
            
            customer c = new customer(nameTF.getText(),cnicTF.getText(),addressTF.getText(),phoneTF.getText()); 
            if(hallTF.getText().equals("Silver")) {
                try {
                    new silverHall1(Integer.parseInt(idTF.getText()),mov,c).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(customerDetail.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false); 
            }
            if(hallTF.getText().equals("Gold")) {
                try {
                    new goldHall1(Integer.parseInt(idTF.getText()),mov,c).setVisible(true);
                    this.setVisible(false);
                } catch (IOException ex) {
                    Logger.getLogger(customerDetail.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(hallTF.getText().equals("Platinum")) {
                try {
                    new platHallUI(Integer.parseInt(idTF.getText()),mov,c).setVisible(true);
                    this.setVisible(false);
                } catch (IOException ex) {
                    Logger.getLogger(customerDetail.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void timeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTFActionPerformed

    private void oldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldActionPerformed
        
        new_customer = false;
        nameTF.setText("");
        phoneTF.setText("");
        addressTF.setText("");
        cnicTF.setText("");
        
        
        verifyButton.setVisible(true);
        backButton.setVisible(true);
        nextButton.setVisible(false);
        nameTF.setVisible(false);
        cnicTF.setVisible(true);
        addressTF.setVisible(false);
        phoneTF.setVisible(false);
        nameLabel.setVisible(false);
        cnicLabel.setVisible(true);
        addressLabel.setVisible(false);
        phoneLabel.setVisible(false);
    }//GEN-LAST:event_oldActionPerformed

    private void newcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcustomerActionPerformed
        new_customer = true;
        nameTF.setText("");
        phoneTF.setText("");
        addressTF.setText("");
        cnicTF.setText("");
        
        verifyButton.setVisible(false);
        backButton.setVisible(true);
        nextButton.setVisible(true);
        nameTF.setVisible(true);
        cnicTF.setVisible(true);
        addressTF.setVisible(true);
        phoneTF.setVisible(true);
        nameLabel.setVisible(true);
        cnicLabel.setVisible(true);
        addressLabel.setVisible(true);
        phoneLabel.setVisible(true);
          
                        nameTF.setEditable(true);
                        addressTF.setEditable(true);
                        phoneTF.setEditable(true);
                        
    }//GEN-LAST:event_newcustomerActionPerformed

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
         
        
        
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/orclpdb", "cinema", "cinema");
            pst = con.prepareStatement("select * from customer");
            rs = pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
           
            boolean found = false;
           while(rs.next())
            {
                Object[] array = new Object[4];
                
                    array[0] = rs.getString("Name");
                    array[1] = rs.getString("cnic");
                    array[2] = rs.getString("email_address");                   
                    array[3] = rs.getString("phone");
                    
                
                  
               
                    if(array[1].toString().toLowerCase().equals(cnicTF.getText().toLowerCase())) {
                        //dft.addRow(array);
                        
                        backButton.setVisible(true);
        nextButton.setVisible(true);
        nameTF.setVisible(true);
        cnicTF.setVisible(true);
        addressTF.setVisible(true);
        phoneTF.setVisible(true);
        nameLabel.setVisible(true);
        cnicLabel.setVisible(true);
        addressLabel.setVisible(true);
        phoneLabel.setVisible(true);
        
                        
                        
                        nameTF.setText(array[0].toString());
                        addressTF.setText(array[2].toString());
                        phoneTF.setText(array[3].toString());
                        
                        nameTF.setEditable(false);
                        addressTF.setEditable(false);
                        phoneTF.setEditable(false);
                        
                        found = true;
                    }
                    
            }
            if(!found) {
                JOptionPane.showMessageDialog(this, "No customer found with this CNIC.");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(searchMovies.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(searchMovies.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_verifyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                movie m = null;
                new customerDetail(m).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel cnicLabel;
    private javax.swing.JTextField cnicTF;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField hallTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton newcustomer;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton old;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JTextField timeTF;
    private javax.swing.JTextField titleTF;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
}
